worker_processes 1;
pid /tmp/nginx.pid;
error_log /dev/stderr notice;

events {
    worker_connections 256;
}

stream {
    server {
        listen 18444;
        proxy_connect_timeout 5s;
        proxy_timeout 60s;
        proxy_pass mattermost:8065;
    }
}
